opt_out_usage

default_platform(:ios)

ensure_env_vars(
  env_vars: [
    "APPLE_ID_EMAIL",
    # "APPLE_ITC_TEAM_ID",
    "APPLE_DEVELOPER_TEAM_ID",
    "APPLE_API_KEY_ID",
    "APPLE_API_ISSUER_ID",
    "APPLE_API_KEY_PATH",
  ],
)

platform :ios do
  api_key = app_store_connect_api_key(
    key_id: ENV["APPLE_API_KEY_ID"],
    issuer_id: ENV["APPLE_API_ISSUER_ID"],
    key_filepath: ENV["APPLE_API_KEY_PATH"],
    in_house: false
  )

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "App.xcworkspace", scheme: "App", xcargs: "-allowProvisioningUpdates")

    upload_to_app_store(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: true,
      # disabled because not supported when using the App Store Connect API key
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      # Skip verification of a HTML preview of the listing
      force: true,
      overwrite_screenshots: true,
      submission_information: {
        add_id_info_uses_idfa: false,
      },
      phased_release: true,
      skip_screenshots: true,
    )
  end
end
